### ISSUE TITLE
NOAUTH Authentication Required

### ISSUE THREAD

**Issue by amjanoni** [socketry/async-io#46]
Hello, 

I'd like to know if it's possible to use this package with Redis Authentication? I'm using the `rediss://:[password]@[hostname]:[port]/[db`] format but even though I'm having issues with the Authentication.

```
/usr/local/bundle/gems/protocol-redis-0.6.0/lib/protocol/redis/connection.rb:120:in `read_object': NOAUTH Authentication required. (Protocol::Redis::ServerError)
        from /usr/local/bundle/gems/async-redis-0.5.3/lib/async/redis/client.rb:124:in `block in call'
        from /usr/local/bundle/gems/async-pool-0.3.5/lib/async/pool/controller.rb:93:in `acquire'
        from /usr/local/bundle/gems/async-redis-0.5.3/lib/async/redis/client.rb:119:in `call'
        from /usr/local/bundle/gems/protocol-redis-0.6.0/lib/protocol/redis/methods/generic.rb:50:in `exists'
        from /app/lib/storage/indexes.rb:49:in `initialize'
        from /app/lib/storage/indexes.rb:25:in `new'
        from /app/lib/storage/indexes.rb:25:in `index_by'
        from /app/storages/client.rb:12:in `<class:Client>'
        from /app/storages/client.rb:1:in `<top (required)>'
        from /app/lib/storage.rb:193:in `require'
        from /app/lib/storage.rb:193:in `each'
        from /app/lib/storage.rb:193:in `block in <top (required)>'
        from /usr/local/bundle/gems/async-1.28.9/lib/async/task.rb:265:in `block in make_fiber'
```

**Comment by amjanoni** [comment]
Wrong Repo, sorry
