### ISSUE TITLE
async-io `Async::IO::Endpoint#connect` should work without Async reactor

### ISSUE THREAD

**Issue by mrhardikjoshi** [socketry/async-io#56]
Hello Everyone,

I am using [echo/client.rb example](https://github.com/socketry/async-io/blob/main/examples/echo/client.rb) without having `Async` wrapper call around it. I am aware some of this gem's feature like `SharedEndpoint` and `Trap` won't work without Async reactor, But I am focused on Endpoint connect/close, read/write and similar operations. As per my understanding those do not require to be run within Async reactor.

Following is how my changed example of `echo/client.rb`  looks like:

```
require 'async'
require 'async/io/host_endpoint'
require 'async/io/stream'

endpoint = Async::IO::Endpoint.tcp('localhost', 4578)
# peer = endpoint.connect        # doesn't work
peer = Sync { endpoint.connect } # Works
stream = Async::IO::Stream.new(peer)

while true
  sleep 1
  stream.puts "Hello World!"
  puts stream.gets.inspect
end
```

This doesn't works when `endpoint.connect` is not wrapped in Async/Sync block. With following error

```
$ruby test.rb
.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/async-2.2.1/lib/async/task.rb:178:in `current': No async task available! (RuntimeError)
	from .rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/async-io-1.34.0/lib/async/io/host_endpoint.rb:55:in `connect'
	from test.rb:8:in `<main>'
``` 
Above exception is raised [here](https://github.com/socketry/async-io/blob/386f2e001e0f849f717addf8e826749039c7b485/lib/async/io/host_endpoint.rb#L55) while trying to get the current task `task = Task.current`. This current task is only used for annotation [here](https://github.com/socketry/async-io/blob/ba89ff1ca1375e69b20d7fe5233811d8d2f7be10/lib/async/io/socket.rb#L121) and [here](https://github.com/socketry/async-io/blob/ba89ff1ca1375e69b20d7fe5233811d8d2f7be10/lib/async/io/socket.rb#L136). (I didn't use local address to bind so it won't need `task` to created another fiber => [reference](https://github.com/socketry/async-io/blob/ba89ff1ca1375e69b20d7fe5233811d8d2f7be10/lib/async/io/socket.rb#L124-L131)).

So my question: Is it correct to use Async::IO without Async reactor like above? and Should we change `Async::IO::Endpoint#connect` and `Async::IO::Socket.connect` methods to get the current task without raising exception and work outside of reactor too?

Thank you :)

**Comment by webgago** [comment]
Hey @mrhardikjoshi,

Pretty much everything related to async ecosystem  should be run inside a reactor. 

You can check how it works in falcon server, ex. https://github.com/socketry/falcon/blob/main/lib/falcon/command/supervisor.rb#L81

```
Async do
  endpoint.connect do |socket|
    stream = Async::IO::Stream.new(socket)
    # your code here
  end
end
```

**Comment by ioquatix** [comment]
Thanks for your question and thanks @webgago for your answer, which is mostly correct.

That being said, there is no reason why the endpoint abstraction needs to run in async, and I'm working on extracting it out of `Async::IO` in the future, but there are some missing nice to have features in core Ruby which make removing the Async dependency a little painful right now.

In the mean time, you CAN use `Addrinfo` or `TCPServer` if you prefer native interfaces. As long as you run it inside an `Async` block, it will be event driven on Ruby 3.1+.
